


GET http://127.0.0.1:8000/api/v1/order/3/
Authorization: Token user2cnee
Content-Type: application/json


###___Размещение заказа покупателем
POST http://127.0.0.1:8000/api/v1/order/1/
Authorization: Token user2cnee
Content-Type: application/json

{ "stock_list": 1,
  "ship_to":2,
  "items": [
    {"id":  3,
    "bags": 1},
    {"id":  4,
    "bags":  1},
    {"id": 151,
    "bags": 1},
    {"id": 154,
    "bags": 1}
  ]
}
###___обновление заказа
PUT http://127.0.0.1:8000/api/v1/order/3/
Authorization: Token user1staff
Content-Type: application/json

{
  "shipment_date":  "2023-05-01",
  "status":  "confirmed"
}
###___изменение заказа заказчиком___
PUT http://127.0.0.1:8000/api/v1/order/3/
Authorization: Token user2cnee
Content-Type: application/json

{
  "ship_to":  3,
  "items": 12

}
###_____________________Stock/Items/<pk>/_______________________________________________________________________________
### Запрос позиций из стока покупателем
GET http://127.0.0.1:8000/api/v1/stock/items/13/
Authorization: Token user2cnee
Content-Type: application/json
### Запрос позиций из стока поставщиком
GET http://127.0.0.1:8000/api/v1/stock/items/13/
Authorization: Token user3shpr
Content-Type: application/json
### Запрос позиций из стока постуавщиком/клиентом
GET http://127.0.0.1:8000/api/v1/stock/items/13/
Authorization: Token user4shpr/cnee
Content-Type: application/json
### Запрос позиций из стока staff
GET http://127.0.0.1:8000/api/v1/stock/items/13/
Authorization: Token user1staff
Content-Type: application/json

###______________________Stock/upload/<pk>/_____________________________________________________________________________
### Загрузка позиций к стоку поставщиком/ поставщиком-клиентом
POST http://127.0.0.1:8000/api/v1/stock/upload/13/
Authorization: Token user3shpr
Content-Type: application/json

{
"url": "https://github.com/dsamoob/Diplom_bdt/blob/main/Singapore_stock.xls?raw=true"
}
### Обновление позиций в стоке пользователем staff (российское название и цена продажи)
POST http://127.0.0.1:8000/api/v1/stock/upload/13/
Authorization: Token user1staff
Content-Type: application/json

{
"url": "https://github.com/dsamoob/Diplom_bdt/blob/main/Singapore_Stock_sale_prices.xls?raw=true"
}

###______________________Stock/<pk>____________________________________________________________________________________
###___Получение сток листов работником
GET http://127.0.0.1:8000/api/v1/stock/8/
Authorization: Token user1staff
Content-Type: application/json
###___Получение сток листов покупателем по ид
GET http://127.0.0.1:8000/api/v1/stock/13/
Authorization: Token user2cnee
Content-Type: application/json
###___Получение всех активных сток листов покупателем
GET http://127.0.0.1:8000/api/v1/stock/
Authorization: Token user2cnee
Content-Type: application/json
###___Получение сток листов поставщиком
GET http://127.0.0.1:8000/api/v1/stock/8/
Authorization: Token user3shpr
Content-Type: application/json
###___Получение сток листов поставщиком/покупателем
GET http://127.0.0.1:8000/api/v1/stock/8/
Authorization: Token user4shpr/cnee
Content-Type: application/json


###___Размещение сток листа поставщиком, поставщиком/покупателем
POST http://127.0.0.1:8000/api/v1/stock/
Authorization: Token user3shpr
Content-Type: application/json

{
  "company": 3,
  "orders_till_date" : "2023-05-07",
  "shipment_date": "2023-06-07",
  "stock_type": 1,
  "bags_quantity": 1,
  "box_weight": 13.4,
  "freight_rate": 5.5,
  "ship_from": 4,
  "transport_type": "Air"

}
###___Изменение сток листа поставщиком или поставщиком/покупателем
PUT http://127.0.0.1:8000/api/v1/stock/9/
Authorization: Token user3shpr
Content-Type: application/json

{
  "company": 3,
  "orders_till_date" : "2023-05-12",
  "shipment_date": "2023-05-13",
  "stock_type": 1,
  "bags_quantity": 1,
  "box_weight": 13.4,
  "freight_rate": 6846.57,
  "ship_from": 1,
  "transport_type": "Air",
  "currency_type": "USD"

}
###___Изменение сток листа пользователем staff
PUT http://127.0.0.1:8000/api/v1/stock/13/
Authorization: Token user1staff
Content-Type: application/json

{
  "orders_till_date" : "2023-05-29",
  "shipment_date": "2023-05-30",
  "status": "offered",
  "name": "Сингапур 2023-05-30",
  "currency_rate": 83.5
}
###___Проверка метода пут для пользователя cnee
PUT http://127.0.0.1:8000/api/v1/stock/9/
Authorization: Token user2cnee
Content-Type: application/json

###___Удаление сток листа поставщиком
DELETE http://127.0.0.1:8000/api/v1/stock/9/
Authorization: Token user3shpr
Content-Type: application/json
###___Удаление сток листа staff
DELETE http://127.0.0.1:8000/api/v1/stock/1/
Authorization: Token user1staff
Content-Type: application/json

###____________________________Stock/<PK> finished_____________________________________________________________________

###___ShipperAddresses___
PUT http://127.0.0.1:8000/api/v1/user/details/shipto/1/
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json

{
  "city": 5,
  "company": 6,
  "street": "pulyanкi",
  "bld": 313,
  "contact_person": "ivцan",
  "phone": "23534у645"
}
###

GET http://127.0.0.1:8000/api/v1/user/details/shipto/
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json

###
DELETE http://127.0.0.1:8000/api/v1/user/details/shipto/1/
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/v1/user/details/shipto/
Authorization: Token user4shpr
Content-Type: application/json

{
  "city": 2,
  "company": 1,
  "street": "pulyanкi",
  "bld": 313,
  "contact_person": "ivцan",
  "phone": "23534у645",
  "ship_target": "ship_to"

}
###
GET http://127.0.0.1:8000/api/v1/user/details/shipto/
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json



### ___User Company _____
PUT http://127.0.0.1:8000/api/v1/user/details/company/16/
Authorization: Token 14215596090f7653a9f8eea4b8ed6a3d5356e636
Content-Type: application/json

{
    "name":  "alesdfksia",
    "city": 3,
    "street": "Jalan Lekar",
    "bld": 21231,
    "bank_details": "HSCB Bank Singapore, A/S 80000000"
  }
###
POST http://127.0.0.1:8000/api/v1/user/details/company
Authorization: Token user2cnee
Content-Type: application/json

{
    "name":  "alesdfksia",
    "city": 3,
    "street": "Jalan Lekar",
    "bld": 21231,
    "bank_details": "HSCB Bank Singapore, A/S 80000000"
  }
###
POST http://127.0.0.1:8000/api/v1/user/details/company
Authorization: Token user4shpr
Content-Type: application/json

{
    "name":  "КолбаскиООО",
    "city": 4,
    "street": "Улица восстания негритят",
    "bld": 18,
    "bank_details": "какой-то банк"
  }
###
DELETE http://127.0.0.1:8000/api/v1/user/details/company/16/
Authorization: Token 14215596090f7653a9f8eea4b8ed6a3d5356e636
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/v1/user/details/company/17/
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json

###___UserDetails____
POST http://127.0.0.1:8000/api/v1/user/details
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json

{
  "first_name": "Ego4r"
}
###
GET http://127.0.0.1:8000/api/v1/user/details
Authorization: Token 086c45927877236e20da382bc1b926b376b66cab
Content-Type: application/json



###___StockTypes___
POST http://127.0.0.1:8000/api/v1/filldb/stocktypes/
Authorization: Token user1staff
Content-Type: application/json

{
  "stock_types": [
    {"name":  "freshwater"},
    {"name": "plants"},
    {"name": "marine"}
]
}
###
GET http://127.0.0.1:8000/api/v1/filldb/stocktypes/
Authorization: Token user1staff
Content-Type: application/json


### ______Загрузка стоимостей фрахта в дб ______ и их проверка
POST http://127.0.0.1:8000/api/v1/filldb/freight/
Authorization: Token user1staff
Content-Type: application/json

{
  "state": "Россия",
  "url": "https://github.com/dsamoob/Diplom_bdt/blob/3d523005648fff47a3a7566f5e77ace0dcd2619e/freightrates.xls?raw=true"
}

###
GET http://127.0.0.1:8000/api/v1/filldb/freight/110/
Authorization: Token user1staff
Content-Type: application/json

{
    "city": "Хабаровск"
}

### _____Загрузка стран и городов в дб____ и их проверка
POST http://127.0.0.1:8000/api/v1/filldb/state/
Authorization: Token user1staff
Content-Type: application/json

{
  "state": [
    {"name":"Россия",
      "cities": [
        {"name": "Москва"},
        {"name":  "Владивосток"},
        {"name":  "Салехард"},
        {"name": "Екатеринбург"},
        {"name": "Новосибирск"},
        {"name":  "Сочи"},
        {"name": "Ростов-на-Дону"}
      ]
    },
    {"name": "Казахстан",
      "cities": [
        {"name": "Астана"},
        {"name": "Караганда"}
      ]
    },
    {"name":  "Республика Беларусь",
      "cities": [
        {"name": "Минск"},
        {"name": "Гомель"}
    ]}
  ]
}
###
GET http://127.0.0.1:8000/api/v1/filldb/state/
Authorization: Token user1staff
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/v1/filldb/state/7/
Authorization: Token 1cc10e80a3027cfa31c7a0cf348112204c06476f
Content-Type: application/json
###
POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
  "first_name": "first_cnee",
  "last_name": "first_cnee_last_name",
  "email": "e.belov@bdt.ru",
  "password": "Amd33oof",
  "username": "cnee_first",
  "type": "cnee",
  "phone": "+79991231234482"
}