# Generated by Django 4.1.7 on 2023-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shpr', 'Магазин'), ('cnee', 'Покупатель'), ('staff', 'Работник')], default='cnee', max_length=5, verbose_name='Тип пользователя'),
        ),
    ]
