# Generated by Django 4.1.7 on 2023-04-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='backend.state'),
        ),
    ]
