# Generated by Django 4.1.7 on 2023-04-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_city_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='backend.state'),
        ),
    ]
